server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://apiprodutos.cph05dvyngug.us-east-1.rds.amazonaws.com:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true