name: Continuous Integration with Github Actions

on:
  push:
    branches: #Suporta uma lista de branchs
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: andredejesus
        password: a85628411

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
        
    - name: Build Application JAR
      working-directory: ./API-produto/
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./
      run: docker compose build

    - name: Create tag, and push docker image to Amazon ECR
      run: |
        docker tag api-produtos-ecr:latest 452284028608.dkr.ecr.us-east-1.amazonaws.com/api-produtos-ecr:${{ github.run_id }}
        docker tag api-produtos-ecr:latest 452284028608.dkr.ecr.us-east-1.amazonaws.com/api-produtos-ecr:latest

        docker push 452284028608.dkr.ecr.us-east-1.amazonaws.com/api-produtos-ecr:${{ github.run_id }}
        docker push 452284028608.dkr.ecr.us-east-1.amazonaws.com/api-produtos-ecr:latest

     # Realiza o download do json da task definition autal e salva na memoria
    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition ${{ secrets.TASK_DEFINITION_NAME }} --query taskDefinition > task-definition.json
        
    #Responsável por gerar uma nova task definition   
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ secrets.CONTAINER_NAME }}
        image: ${{ secrets.IMAGE_REPO_URL }}:latest

    #Responsável por realizar o deploy da nova task definition para o ECS
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ secrets.SERVICE_NAME }}
        cluster: ${{ secrets.CLUSTER_NAME }}
        wait-for-service-stability: true