name: Continuous Integration with Github Actions

on:
  push:
    branches: #Suporta uma lista de branchs
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Application JAR
      working-directory: ./projeto-api-produtos/API-produto
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./projeto-api-produtos
      run: docker compose build
